### ISSUE TITLE
Encryption Error

### ISSUE THREAD

**Issue by ghost** [yntha/bitlife-edit#1]
An error occur when encrypting the "MissionVars" file, but doing the same thing with "MonetizationVars" doesn't produce the same error.

**"The Error"**

``Unhandled exception. System.Runtime.Serialization.SerializationException: Type 'System.Text.Json.JsonElement' in Assembly 'System.Text.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' is not marked as serializable.
   at System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers(Type type)
   at System.Runtime.Serialization.FormatterServices.<>c.<GetSerializableMembers>b__5_0(MemberHolder mh)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitMemberInfo()
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Type objectType, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteArray(WriteObjectInfo objectInfo, NameInfo memberNameInfo, WriteObjectInfo memberObjectInfo)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, BinaryFormatterWriter serWriter)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
   at Program.EncryptVarFile()
   at Program.Main(String[] args)``

**".json file"**

[MissionVars.json](https://github.com/user-attachments/files/16612223/MissionVars.json)

Even without the "AcquiredSunglassesArray" & "AcquiredHeadwearArray" followed by a bunch of numbers in the .json file, it still doesn't work, i didn't add them there btw.

**Comment by yntha** [comment]
Just to clear something up, the `AcquiredSunglassesArray` and `AcquiredHeadwearArray` fields are both part of the game. The tool itself does not add any extra fields to the output.

**Comment by yntha** [comment]
If you run into any other issues, please create a new issue.
